{
	"version": 1595598694,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/tilemap1.png",
		"images/trunk-sheet0.png",
		"images/treetop-sheet0.png",
		"images/tree_-sheet0.png",
		"images/bush-sheet0.png",
		"images/crate-sheet0.png",
		"images/tree_2-sheet0.png",
		"images/mushroom_-sheet0.png",
		"images/mushroom_2-sheet0.png",
		"images/cementstair-sheet0.png",
		"images/rock-sheet0.png",
		"images/waterfall-sheet0.png",
		"images/pencuri-sheet0.png",
		"images/creep-sheet0.png",
		"images/barrel-sheet0.png",
		"images/tree-sheet0.png",
		"images/minimap-sheet0.png",
		"images/point-sheet0.png",
		"images/tarun-sheet0.png",
		"images/tarun-sheet1.png",
		"images/lives-sheet0.png",
		"images/lives-sheet1.png",
		"images/particles.png",
		"images/darah.png",
		"images/bg.png",
		"images/healthborder-sheet0.png",
		"images/healthbar-sheet0.png",
		"images/sprite-sheet0.png",
		"images/creepposition-sheet0.png",
		"images/creep_gun-sheet0.png",
		"images/box_push-sheet0.png",
		"images/key-sheet0.png",
		"images/key-sheet1.png",
		"images/key2-sheet0.png",
		"images/peti-sheet0.png",
		"images/star-sheet0.png",
		"images/coin_end-sheet0.png",
		"images/tiledbackground2.png",
		"images/tiledbackground.png",
		"images/icontarun-sheet0.png",
		"images/tiledbackground4.png",
		"images/set-sheet0.png",
		"images/pistol-sheet0.png",
		"images/dor-sheet0.png",
		"images/batas-sheet0.png",
		"images/papaninfo-sheet0.png",
		"images/level-sheet0.png",
		"images/gembok-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/healthbar2-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/gembok3-sheet0.png",
		"images/backpilihlevel-sheet0.png",
		"images/restart-sheet0.png",
		"images/home-sheet0.png",
		"media/t_creep gun.ogg",
		"media/t_darah berkurang.ogg",
		"media/t_death.ogg",
		"media/t_kunci collect.ogg",
		"media/t_start.ogg",
		"media/t_win.ogg",
		"media/t_tarun menembak.ogg",
		"media/t_you lose.ogg",
		"media/t__menu_african wildlife.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}